version: 2.1

orbs:
  docker: circleci/docker@0.5.20


jobs:
  # Build the docker image for nasqar
  build:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: aymanm/nasqarall
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  push:
    executor: docker/machine
    steps:
      - setup_remote_docker
      - docker/push:
          digest-path: /tmp/digest.txt
          image: aymanm/nasqarall
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  push_with_tags:
    executor: docker/machine
    steps:
      - setup_remote_docker
      - docker/push:
          digest-path: /tmp/digest.txt
          image: aymanm/nasqarall
          tag: 'latest,nasqarall'
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  terraform_plan:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          command: |
            bash .circleci/install_ci_deps.sh
            cd auto-deployment/terraform-state
            terraform init; terraform plan
            cd ../infrastructure
            terraform init; terraform plan

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - terraform_plan
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
      - push_with_tags:
          requires:
            - build
          filters:
            branches:
              only: master
