version: 2.1

orbs:
  docker: circleci/docker@0.5.20


jobs:
  # Build the docker image for nasqar
  build:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: aymanm/nasqarall
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  push:
    executor: docker/machine
    steps:
      - setup_remote_docker
      - docker/push:
          digest-path: /tmp/digest.txt
          image: aymanm/nasqarall
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
