version: 2.1

orbs:
  docker: circleci/docker@0.5.20

jobs:
  # Docker build steps
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: aymanm/nasqarall
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  push:
    executor: docker/docker
    steps:
      - docker/push:
          digest-path: /tmp/digest.txt
          image: aymanm/nasqarall
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - push:
          requires:
            - build
